services:
  laravel:
    build:
      context: .
      dockerfile: dockerfile
      target: prod
      args:
        DEV_MODE: "true"
    container_name: ground-zero
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - SESSION_DRIVER=${SESSION_DRIVER}
