version: "3.8"
services:
  php:
    build:
      context: .
      target: development
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    ports:
      - 80:8080
    volumes:
      - .:/var/www/html
