services:
  ground-zero:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${APP_ENV}
    container_name: ground-zero
    restart: unless-stopped
    working_dir: /var/www/html
    # ports:
    #   - "8080:80" # local port
      # - "5173:5173" # local vite
    # volumes:
      # - .:/var/www/html:cached # local devcontainer
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - SESSION_DRIVER=${SESSION_DRIVER}

# local network
#     networks:
#       - npm_network

# networks:
#   npm_network:
#     external: true
