services:
  laravel:
    container_name: laravel
    restart: unless-stopped
    working_dir: /var/www/html
    build:
      context: .
      target: development
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        PHP_VERSION: 8.3
    volumes:
      - .:/var/www/html
    ports:
      - 80:8080
      - 9003:9003
    environment:
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 idekey=PHPSTORM
    networks:
      - npm_network

networks:
  npm_network:
    external: true
