services:
  laravel:
    container_name: ground-zero
    restart: unless-stopped
    working_dir: /var/www/html
    build:
      context: .
      target: development
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        PHP_VERSION: 8.3
    # volumes:
      # - .:/var/www/html:cached
      # - .vendor:/var/www/html/vendor
      # - .node_modules:/var/www/html/node_modules
    # ports:
    #   - 80:8080
    networks:
      - npm_network

networks:
  npm_network:
    external: true
