services:
  laravel:
    build:
      context: .
      dockerfile: dockerfile
      target: dev
      args:
        DEV_MODE: "true"
    container_name: ground-zero
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    ports:
      - "8080:8080"
      - "8000:8000"