services:
  laravel:
    container_name: ground-zero-production
    restart: unless-stopped
    working_dir: /var/www/html
    build:
      context: .
      target: production
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        PHP_VERSION: 8.3
    ports:
      - 8080:8080
    volumes:
      - ./storage:/var/www/html/storage
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nginx-proxy-manager-network

networks:
  nginx-proxy-manager-network:
    external: true
